### ISSUE TITLE
An exception was thrown: read access violation.

### ISSUE THREAD

**Issue by mxlin043** [lei65537/Visual_Driven_Mesh_Repair#2]
Hi, your work is so amazing and meaningful!

There exists some problems when I run the project according to the Tutorial in README.

The error message shows as following:

An exception was thrown: read access violation.
** std :: _ Vector_alloc <std :: _ Vec_base_types <double, std :: allocator <double>>> :: _ Myfirst ** (...) returns 0x1F10CDEE420. Appeared

I found that it seems to have some connection to do with Line 210 in OffScreenRender.cpp.
The IDmask have the negative number while the triangle id in the offscreen render is from 1.

Is this problem to do with Solution Platform? Win32 or x64?

**Comment by haopan** [comment]
Hi. The project should be built in x64 platform. The vector access violation happens for a double vector, but IDmask is an integer vector. So it seems you are not pinpointing the exact error occurrence.
