### ISSUE TITLE
Problem with freeglut 

### ISSUE THREAD

**Issue by kimihailv** [lei65537/Visual_Driven_Mesh_Repair#5]
Hello, thanks for your work. 
When I try to build your library cmake stops with this error:

No build type selected, default to Release 
OPENMP FOUND 
Using header-only CGAL 
Targetting Visual Studio 15 2017 
Target build enviroment supports auto-linking 
Using VC14 compiler. 
Generator uses intermediate configuration directory: $(Configuration) 
CMake Deprecation Warning at C:/dev/CGAL-4.12.1/cmake/modules/CGAL_TweakFindBoost.cmake:29 (cmake_policy): 
  The OLD behavior for policy CMP0077 will be removed from a future version 
  of CMake. 
 
  The cmake-policies(7) manual explains that the OLD behaviors of all 
  policies are deprecated and that a policy should be set to OLD only under 
  specific short-term circumstances.  Projects should be ported to the NEW 
  behavior and not rely on setting a policy to OLD. 
Call Stack (most recent call first): 
  C:/dev/CGAL-4.12.1/cmake/modules/CGAL_SetupBoost.cmake:18 (include) 
  C:/dev/CGAL-4.12.1/cmake/modules/CGAL_SetupCGALDependencies.cmake:52 (include) 
  C:/dev/CGAL-4.12.1/lib/cmake/CGAL/CGALConfig.cmake:106 (include) 
  C:/dev/CGAL-4.12.1/CGALConfig.cmake:6 (include) 
  CMakeLists.txt:55 (find_package) 
 
 
Boost include dirs: C:/local/boost_1_68_0 
Boost libraries:     
Visual Leak Detector (VLD) is not found. 
Multi-configuration CMake generator: cannot display flags 
CMake Deprecation Warning at C:/dev/CGAL-4.12.1/cmake/modules/CGAL_TweakFindBoost.cmake:29 (cmake_policy): 
  The OLD behavior for policy CMP0077 will be removed from a future version 
  of CMake. 
 
  The cmake-policies(7) manual explains that the OLD behaviors of all 
  policies are deprecated and that a policy should be set to OLD only under 
  specific short-term circumstances.  Projects should be ported to the NEW 
  behavior and not rely on setting a policy to OLD. 
Call Stack (most recent call first): 
  C:/dev/CGAL-4.12.1/cmake/modules/UseCGAL.cmake:27 (include) 
  CMakeLists.txt:59 (include) 
 
 
Code taken from Git branch: n/a 
Requested component: MPFR 
Requested component: GMP 
Find CGAL successfully. 
CMake Deprecation Warning at Extern/glew/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED): 
  Compatibility with CMake < 2.8.12 will be removed from a future version of 
  CMake. 
 
  Update the VERSION argument <min> value or use a ...<max> suffix to tell 
  CMake that the project does not need compatibility with older versions. 
 
 
Found MOSEK: C:/Program Files/Mosek/8/tools/platform/win64x86/bin/mosek64_8_1.lib   
Configuring done 
CMake Error: install(EXPORT "FreeGLUTTargets" ...) includes target "freeglut" which requires target "CGAL" that is not in any export set. 
CMake Error: install(EXPORT "FreeGLUTTargets" ...) includes target "freeglut_static" which requires target "CGAL" that is not in any export set. 
CMake Error in Extern/freeglut/CMakeLists.txt: 
  export called with target "freeglut" which requires target "CGAL" that is 
  not in any export set. 
 
 
CMake Error in Extern/freeglut/CMakeLists.txt: 
  export called with target "freeglut_static" which requires target "CGAL" 
  that is not in any export set.
  
CGAL_DIR var is set, path to gmp lib is also added to PATH var. 
Could you please help?

**Comment by haopan** [comment]
Seems like a CGAL script problem https://github.com/CGAL/cgal/pull/3922 . Maybe you can try with the updated CGAL.

**Comment by kimihailv** [comment]
I could build with updated cgal, thanks!
