### ISSUE TITLE
Only one output mesh

### ISSUE THREAD

**Issue by kimihailv** [lei65537/Visual_Driven_Mesh_Repair#6]
For some meshes program returns only one *_vd.ob, *_opt.obj and *_hr.obj are absent. Is it expected behavior?

**Comment by lei65537** [comment]
For some simple meshes that need no optimization step, the output might be *_optN.obj or *_opt_HRN.obj. If you don't have these files, the program may not exit properly. You could try to uncomment _RECORD_ERROR_LOGS in the stdafx.h to enable the log file and see what's going wrong.

**Comment by kimihailv** [comment]
> For some simple meshes that need no optimization step, the output might be *_optN.obj or *_opt_HRN.obj. If you don't have these files, the program may not exit properly. You could try to uncomment _RECORD_ERROR_LOGS in the stdafx.h to enable the log file and see what's going wrong.

I was not clear, I meant the program outputs only _vd.obj, but README says that program should also output _opt.obj and _hr.obj

**Comment by lei65537** [comment]
Yes, normally the program would generate those two files, and we did not find meshes that fail to do so in our previous experiments. Thus I need more information to tell what's going wrong. 

> > For some simple meshes that need no optimization step, the output might be *_optN.obj or *_opt_HRN.obj. If you don't have these files, the program may not exit properly. You could try to uncomment _RECORD_ERROR_LOGS in the stdafx.h to enable the log file and see what's going wrong.
> 
> I was not clear, I meant the program outputs only _vd.obj, but README says that program should also output _opt.obj and _hr.obj

**Comment by kimihailv** [comment]
_DEBUG_LOGS_ALL.txt is empty. 
Mesh with mtl: [problem_mesh.zip](https://github.com/lei65537/Visual_Driven_Mesh_Repair/files/7110008/problem_mesh.zip)
Thank you very much for your help.

**Comment by artonson** [comment]
@lei65537 @haopan Hello! Any chance you could suggest, which meshes must work properly and which may fail, is there any way to diagnose or predict this?

**Comment by lei65537** [comment]
> _DEBUG_LOGS_ALL.txt is empty.
> Mesh with mtl: [problem_mesh.zip](https://github.com/lei65537/Visual_Driven_Mesh_Repair/files/7110008/problem_mesh.zip)
> Thank you very much for your help.

Hi, I have recompiled the program from scratch and tested it on the mesh you sent. However, I did not get any failure, and here are the results. https://drive.google.com/drive/folders/1HvI8Q0Re_pC4PHW3xy9B3-sBWheQrCOb?usp=sharing

For your information, it was compiled on VS2019, boost_1_77_0, CGAL4.14.3.

**Comment by lei65537** [comment]
> @lei65537 @haopan Hello! Any chance you could suggest, which meshes must work properly and which may fail, is there any way to diagnose or predict this?

Theoretically, the program could work on any meshes. Yet in our previous experiments, we found it time-consuming when the mesh has way too many components. So we have set a bar _MAX_CC_NM_FOR_PREPROCESSING in include/stdafx.h to filter them out (already disabled in the current release).
