### ISSUE TITLE
Losing Texture Coordinates

### ISSUE THREAD

**Issue by FishWoWater** [lei65537/Visual_Driven_Mesh_Repair#7]
Hi! Thanks for your nice work!

I downloaded your pre-processed ShapeNet dataset and noticed that UV coordinates are missing after repairing(actually they did exist before repairing). 

Is there any way to maintain or obtain the UV coords for repaired meshes?

By the way, could you please share some resources about remeshing with UVs?

Thank you very much, wish you a nice day~

**Comment by lei65537** [comment]
Hi, 
Yes, the released code does not have the UV coordinates. But as shown in our paper, you could modify the pipeline to keep them, since for each triangle facet in the output mesh the vertex is either from the original mesh or newly inserted to resolve the intersection.

**Comment by FishWoWater** [comment]
Thank you!  I will have a try~
